name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: piwik_tests
        ports:
          - 3306:3306
        tmpfs:
          - /var/lib/mysql
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: true
      matrix:
        tests: [ 'unit','system','integration' ]

    name: ${{ matrix.tests }} tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: '4.x-dev'
          lfs: true
          submodules: recursive

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_sqlite, gd, redis
          ini-values: post_max_size=256M, max_execution_time=10000, memory_limit=4024M
          tools: composer:v2
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: '12'

      - name: install fonts
        run: |
             git clone --recursive https://github.com/google/woff2.git ../fonts_woff2
             cd ../fonts_woff2
             make clean all

      - name: installing node/puppeteer
        working-directory: ./tests/lib/screenshot-testing
        run: npm install

      - name: installing config.ini.php && Adjusting phpunit.xml && tmp/ sub-directories
        run: |
          cp ./tests/travis/config.ini.travis.php  ./config/config.ini.php
          cp ./tests/PHPUnit/phpunit.xml.dist ./tests/PHPUnit/phpunit.xml
          mkdir -p ./tmp/assets
          mkdir -p ./tmp/cache
          mkdir -p ./tmp/latest
          mkdir -p ./tmp/logs
          mkdir -p ./tmp/sessions
          mkdir -p ./tmp/templates_c
          mkdir -p ./tmp/tcpdf
          mkdir -p ./tmp/climulti
          chmod a+rw ./tests/lib/geoip-files || true
          chmod a+rw ./plugins/*/tests/System/processed || true
          chmod a+rw ./plugins/*/tests/Integration/processed || true
#
#      - name: Setup Nginx
#        run: |
#          docker run --name nginxapp -v /home/runner/work/matomo/matomo:/var/www/ -v /home/runner/work/matomo/matomo/.github/scripts/piwiki_nginx.config:/etc/nginx/conf -p 80:80 -d nginx
#          docker ps

      - name: Install dependencies
        run : composer install

      - name: Run PHP on 3000
        run : |
               sudo apt-get install tmux
               tmux new-session -d -s "php" php -S localhost:3000

      - name: Test runing
        run: ./console tests:run ${{ matrix.tests }}
