name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: piwik_tests
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: true
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0', '8.1' ]
        stability: [prefer-lowest, prefer-stable]
        include:
          - php: '8.1'
            stability: prefer-stable

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: '4.x-dev'
          lfs: true
          submodules: recursive

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_sqlite, gd, redis
          ini-values: post_max_size=256M, max_execution_time=3000, memory_limit=1024M
          tools: composer:v2
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
            node-version: '12'

      - name: install fonts
        run: |
             git clone --recursive https://github.com/google/woff2.git ../fonts_woff2
             cd ../fonts_woff2
             make clean all

      - name: installing node/puppeteer
        working-directory: ./tests/lib/screenshot-testing
        run: npm install

      - name: installing config.ini.php
        run: cp ./tests/travis/config.ini.travis.php  ./config/config.ini.php

      - name: install Adjusting phpunit.xml
        run: cp ./tests/PHPUnit/phpunit.xml.dist ./tests/PHPUnit/phpunit.xml

      - name: Create tmp/ sub-directories
        run: |
          mkdir -p ./tmp/assets
          mkdir -p ./tmp/cache
          mkdir -p ./tmp/latest
          mkdir -p ./tmp/logs
          mkdir -p ./tmp/sessions
          mkdir -p ./tmp/templates_c
          mkdir -p ./tmp/tcpdf
          mkdir -p ./tmp/climulti
          chmod a+rw ./tests/lib/geoip-files || true
          chmod a+rw ./plugins/*/tests/System/processed || true
          chmod a+rw ./plugins/*/tests/Integration/processed || true
#
#      - name: Setup Nginx
#        run: |
#          docker run --name nginxapp -v /home/runner/work/matomo/matomo:/var/www/ -v /home/runner/work/matomo/matomo/.github/scripts/piwiki_nginx.config:/etc/nginx/conf -p 80:80 -d nginx
#          docker ps

      - name: Install dependencies
        run : composer install

#      - name: Unit Test
#        run: ./console tests:run unit

      - name: System Test
        run: ./console tests:run system
