name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: piwik_tests
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      redis:
        image: redis:5.0
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: false
      matrix:
        tests: [ 'unit','integration','ui' ]
        parts: [0]
        include:
          - tests: 'system'
            parts: [0,11,21,31,41,51]


    name: ${{ matrix.tests }} tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: '4.x-dev'
          lfs: true
          submodules: recursive

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_sqlite, gd, redis
          ini-values: post_max_size=256M, max_execution_time=10000, memory_limit=4024M
          tools: composer:v2, phpunit:8.5
          coverage: none

      - name: Setup Node
        if: matrix.tests == 'integration'
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: install fonts
        if: matrix.tests =='ui'
        run: |
          git clone --recursive https://github.com/google/woff2.git ../fonts_woff2
          cd ../fonts_woff2
          make clean all

      - name: installing node/puppeteer
        if: matrix.tests == 'integration' || matrix.tests =='ui'
        working-directory: ./tests/lib/screenshot-testing
        run: npm install

      - name: installing config.ini.php && Adjusting phpunit.xml && tmp/ sub-directories
        run: |
          cp ./.github/scripts/config.ini.travis.php  ./config/config.ini.php
          cp ./tests/PHPUnit/phpunit.xml.dist ./tests/PHPUnit/phpunit.xml
          mkdir -p ./tmp/assets
          mkdir -p ./tmp/cache
          mkdir -p ./tmp/latest
          mkdir -p ./tmp/logs
          mkdir -p ./tmp/sessions
          mkdir -p ./tmp/templates_c
          mkdir -p ./tmp/tcpdf
          mkdir -p ./tmp/climulti
          chmod a+rw ./tests/lib/geoip-files || true
          chmod a+rw ./plugins/*/tests/System/processed || true
          chmod a+rw ./plugins/*/tests/Integration/processed || true
      #
      #      - name: Setup Nginx
      #        run: |
      #          docker run --name nginxapp -v /home/runner/work/matomo/matomo:/var/www/ -v /home/runner/work/matomo/matomo/.github/scripts/piwiki_nginx.config:/etc/nginx/conf -p 80:80 -d nginx
      #          docker ps

      - name: Install dependencies
        run: composer install

      - name: Run PHP on 3000
        if: startsWith(matrix.tests,'system') ||  matrix.tests == 'ui'
        run: |
          sudo apt-get install tmux
          tmux new-session -d -s "php" php -S localhost:3000

      - name: Test runing
        if:  matrix.tests == 'unit'
        run: ./console tests:run ${{ matrix.tests }}

      - name: Run System test
        if: startsWith(matrix.tests,'system')
        run: |
          arr=( $(ls | grep 'php'|sed -e 's/\.php$//') )
          total=${#arr[@]}/5
          for item in ${arr[@]:${{ matrix.parts }}:${{ matrix.parts }}+10}
          do
          ./console tests:run System ${item}
          done

      - name: UI tests
        if: matrix.tests == 'ui'
        run: |
          sudo apt-get install ttf-mscorefonts-installer imagemagick imagemagick-doc
          sudo apt-get remove ttf-bitstream-vera

